name: Patch Exynos982x boot images with magisk

on:
  workflow_dispatch:

jobs:
  patch_boot:
    name: Patch boot images and release
    runs-on: ubuntu-latest

    steps:
      - name: Patch boot images with Magisk
        uses: 0xsharkboy/magisk-patch-action@main
        with:
          devices: beyond0lte
          ota_link: https://raw.githubusercontent.com/Evolution-XYZ/OTA/udc/builds/

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV ; ls -R

      - name: Upload patched boot images
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ env.date }}
          tag_name: ${{ github.run_id }}
          make_latest: 'true'
          files: ./script/out/*.img
          